name: Update JSONBin
on:
  workflow_dispatch: # manuell startbar

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      JSONBIN_KEY: ${{ secrets.JSONBIN_KEY }}
      BIN_ID: "DEINE_BIN_ID_HIER" # <-- hier deine Bin-ID eintragen
    steps:
      - name: Update JSONBin
        run: |
          echo '{"message":"Update von GitHub Actions!"}' > data.json
          curl -X PUT \
            -H "Content-Type: application/json" \
            -H "X-Master-Key: $JSONBIN_KEY" \
            --data @data.json \
            https://api.jsonbin.io/v3/b/${BIN_ID}
